### ISSUE TITLE
#'< and #'>

### ISSUE THREAD

**Issue by phoe** [moderninterpreters/markup#1]
How does this library solve the problem of `(< 2 3)` or `(> 2 3)` that is valid Lisp code?

**Comment by tdrhq** [comment]
Yep, handled. It's a subset of HTML, so we require '<' to not be followed by whitespace.

https://github.com/moderninterpreters/markup/blob/master/test-markup.lisp#L187

(the reader is enabled on that file.)

**Comment by phoe** [comment]
OK - nice one!
