### ISSUE TITLE
Templates with multiple children?

### ISSUE THREAD

**Issue by atgreen** [moderninterpreters/markup#12]
Thank you for markup.

I have a situation where I want to use a template, but instead of having one place to @(progn children), I want to inject different content in two places in the template. How should I handle this?

**Comment by tdrhq** [comment]
Typically when need this I write code to break down the children. Be careful though, the children contain both strings and tags,so you might want to filter out the strings first. But here's an example of doing this: https://github.com/screenshotbot/screenshotbot-oss/blob/main/src/core/ui/simple-card-page.lisp#L25

Would love your thoughts on how this can be generalized in a better way.

**Comment by tdrhq** [comment]
(mquery in that code comes from here: https://github.com/screenshotbot/screenshotbot-oss/blob/main/src/util/mquery.lisp, it's like jquery but for markup and is very useful, but I've not extracted it into a library yet)

**Comment by atgreen** [comment]
Thanks for the quick reply.  I see how you handle it...  The good news is
that it can be done!  I will try that, and think about how it could be made
easier.
