### ISSUE TITLE
Parenthesis matching for (< 3 2)

### ISSUE THREAD

**Issue by tdrhq** [moderninterpreters/markup#6]
Emacs seems to be matching the ')' with '<' in the expressin (< 3 2).

In particular paredit-mode fails because it things there are unmatched parenthesis. 

I'm going to look into it, but was hoping you'd have a much more quicker answer :)

**Comment by charJe** [comment]
does `forward-sexp` work? I havent used paredit-mode. also what is the result of `(syntax-after (point))` when the cursor is on `<`

**Comment by tdrhq** [comment]
I disabled paredit-mode, for these:

with buffer (< 3 2) and point at <, forward-sexp goes to ), so that's incorrect.

(syntax-after (point)) gives (4).

**Comment by charJe** [comment]
You can close this issue if that solved your problem.

**Comment by tdrhq** [comment]
@charJe So if I open a new emacs session, this seems to be behaving better.  I'm not able to make it work on my existing Emacs session, so I'm just going to restart it. 
It would be nice if we could make this a minor-mode so that we can turn it on and off for debugging purposes.

**Comment by charJe** [comment]
You should be able to fix the current session by with 
```
(modify-syntax-entry ?< "w" lisp-mode-syntax-table)
(modify-syntax-entry ?> "w" lisp-mode-syntax-table)
```
The nature of syntax tables is very imperative. If I made it a minor mode, I guess having it's own syntax table would mitigate some of these issues.

**Comment by tdrhq** [comment]
Aweomse, thanks, I'll close out this task for now, and I'll reopen if I do find any more issues. Thanks for the quick response on this! You saved me a lot of time trying to debug this myself!
