### ISSUE TITLE
Warning for Undefined Tag.

### ISSUE THREAD

**Issue by charJe** [moderninterpreters/markup#7]
I appreciate the warning or errors I get for unclosed or improperly closed tags. It would be nice to get **compilation** warnings when trying to use undefined tags. What I mean by undefined tags are non-html, non-keyword tags that have not been defined with `deftag` yet. Standard html tags and keyword tags should never cause an undefined tag warning.

**Comment by tdrhq** [comment]
This makes sense, I've definitely been bitten by this before. Will try doing this in the next few days.

**Comment by tdrhq** [comment]
Fixed in https://github.com/moderninterpreters/markup/commit/8ce2b12f247d29a784bcd6763681e23f8722b86a

**Comment by tdrhq** [comment]
One thing that bothers me with this warning is that it doesn't behave the same way as `defuns` do. In particular, if you call compile-file on a file, the order of the functions don't matter. But this mechanism makes it matter. I'm still digging into how I can make this better, AFAICT there isn't an implementation independent way of doing this

**Comment by tdrhq** [comment]
I used an SBCL specific hack instead: https://github.com/moderninterpreters/markup/commit/b75b4523d995e2551d55f776b8c7338f1d154b41, which has a much better user experience but is slightly incorrect (if you have a defun instead of a deftag, it won't show the warning, but would technically still fail at runtime)

I hope I can figure out a hack for Lispworks

**Comment by charJe** [comment]
Your SBCL hack works for me. I'm also getting no warnings whatsoever on Clisp.

**Comment by tdrhq** [comment]
yeah, I didn't want to default to signalling a warning, because that warning would be wrong pretty frequently. So I decided to leave the warnings off for platforms unless I have a way of doing it correctly.
